root: Bio
databases:
  default: biosphere
classes:
  User:
    source: user
    key: user_id
    pattern: '{user_id:int}'
    string: '{login}'
    fields:
      user_id: { type: integer, readonly: true }
      login: { type: string }
      password: { type: string }
      hash: { type: string }
      roles: { type: set }
      email: { type: string }
      room_user: { type: object }
    relations:
      room_user: { class: RoomUser, type: many-to-one, inverse: { name: _user, type: one-to-many }, join: { user_id: user_id } }
  Room:
    source: room
    key: room_id
    pattern: '{room_id:int}'
    string: 'Room #{room_id}'
    fields:
      room_id: { type: integer, readonly: true }
      params: { type: string }
      dt_created: { type: unixtime }
      status: { type: integer }
      users: { type: collection }
  RoomUser:
    source: room_user
    key: room_user_id
    pattern: '{room_user_id:int}'
    string: 'Room #{room_id}'
    fields:
      room_user_id: { type: integer, readonly: true }
      room_id: { type: integer }
      user_id: { type: integer }
      params: { type: string }
      user: { type: object }
      room: { type: object }
    relations:
      user: { class: User, type: many-to-one, inverse: { name: _users, type: one-to-many }, join: { user_id: user_id } }
      room: { class: Room, type: many-to-one, inverse: { name: users, type: one-to-many }, join: { room_id: room_id } }